# Generated by Django 3.2.3 on 2021-05-19 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0002_variablecosts_variablecostsource_variablecostsourcecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcostsourcecategory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='fixedcostsourcecategory',
            name='source',
        ),
        migrations.AddField(
            model_name='fixedcostsource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedcostsourcecategory',
            name='sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.fixedcostsource'),
        ),
    ]
