# Generated by Django 3.2.3 on 2021-05-21 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0004_fixedcosts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedcostsourcecategory',
            name='sources',
        ),
        migrations.AddField(
            model_name='fixedcostsource',
            name='sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.fixedcostsourcecategory'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.fixedcostsourcecategory'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.fixedcostsource'),
        ),
        migrations.AlterField(
            model_name='fixedcostsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='fixedcostsourcecategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
