# Generated by Django 3.2.3 on 2021-05-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20210521_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcostsource',
            old_name='sources',
            new_name='source',
        ),
    ]
