# Generated by Django 3.2.3 on 2021-05-21 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0006_rename_sources_fixedcostsource_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcosts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='fixedcosts',
            table='expense_fixedcosts',
        ),
        migrations.AlterModelTable(
            name='fixedcostsource',
            table='expense_fixedcostsource',
        ),
        migrations.AlterModelTable(
            name='fixedcostsourcecategory',
            table='expense_fixedcostsourcecategory',
        ),
    ]
