# Generated by Django 3.2.3 on 2021-05-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20210521_1642'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fixedcosts',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fixedcostsource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fixedcostsourcecategory',
            table=None,
        ),
    ]
