# Generated by Django 3.2.3 on 2021-05-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0008_auto_20210521_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablecostsourcecategory',
            name='source',
        ),
        migrations.RemoveField(
            model_name='variablecostsourcecategory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='variablecosts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.variablecostsourcecategory'),
        ),
        migrations.AddField(
            model_name='variablecostsource',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.variablecostsourcecategory'),
        ),
        migrations.AddField(
            model_name='variablecostsource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variablecostsourcecategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variablecosts',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.variablecostsource'),
        ),
        migrations.AlterField(
            model_name='variablecosts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
