# Generated by Django 3.2.3 on 2021-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20210521_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcostsource',
            old_name='source',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='variablecostsource',
            old_name='source',
            new_name='category',
        ),
    ]
