# Generated by Django 3.2.3 on 2021-05-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeSourceCategory',
        ),
    ]
