# Generated by Django 3.2.3 on 2021-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_auto_20210521_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomesource',
            old_name='sources',
            new_name='categories',
        ),
    ]
